name: Deploy to GitHub Packages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Run Tests & Check Coverage
      run: |
        cd projet_devops
        mvn -B verify -Pcoverage
      
    - name: Publish to GitHub Packages
      if: success()
      run: |
        cd projet_devops
        mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}